# Используем готовый Docker-образ с Flutter SDK
image: cirrusci/flutter:stable

stages:
  - test
  - build
  - release

# Определение кеша для ускорения сборки
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub-cache/

# Перед каждым job'ом получаем зависимости
before_script:
  - flutter pub get

# Job для запуска тестов
unit_tests:
  stage: test
  script:
    - flutter test

# Job для сборки Debug APK для всех коммитов, кроме тегов
build_apk_debug:
  stage: build
  script:
    - flutter build apk --debug
  artifacts:
    name: "debug-apk-${CI_COMMIT_REF_NAME}"
    paths:
      - build/app/outputs/flutter-apk/app-debug.apk
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_TAG == null

# Job для сборки Release APK, запускается только для тегов
build_apk_release:
  stage: build
  script:
    # Для подписи релиз-сборки необходимо настроить переменные окружения CI/CD:
    # KEYSTORE_BASE64 - содержимое файла keystore в base64
    # KEY_PROPERTIES - содержимое файла key.properties
    # Если они заданы, раскомментируйте следующие строки:
    # - echo "$KEYSTORE_BASE64" | base64 -d > android/app/upload-keystore.jks
    # - echo "$KEY_PROPERTIES" > android/key.properties
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: never
  rules:
    - if: $CI_COMMIT_TAG

# Job для сборки Release App Bundle, запускается только для тегов
build_aab_release:
  stage: build
  script:
    # Так же, как и для APK, требуется настройка подписи
    - flutter build appbundle --release
  artifacts:
    paths:
      - build/app/outputs/bundle/release/app-release.aab
    expire_in: never
  rules:
    - if: $CI_COMMIT_TAG

# Job для создания релиза в GitLab
create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build_apk_release
    - build_aab_release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --description "Autogenerated release for tag $CI_COMMIT_TAG" \
        --assets-link "{\\"name\\":\\"Android APK\\",\\"url\\":\\"${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/raw/build/app/outputs/flutter-apk/app-release.apk?job=build_apk_release\\"}" \
        --assets-link "{\\"name\\":\\"Android App Bundle\\",\\"url\\":\\"${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/raw/build/app/outputs/bundle/release/app-release.aab?job=build_aab_release\\"}"
