script_file_name: v2_dman_v5_config.py
maker_exchange: whitebit
maker_pair: XMR-USDT
taker_exchange: binance_perpetual
taker_pair: XMR-USDT
order_amount: 10.0
profitability_target: 0.06
profitability_min: 0.05
profitability_max: 0.07
leverage: 1
candles_interval: 1m
n_levels: 3
start_spread: 1.0
step_between_orders: 0.8
order_refresh_time: 2700
cooldown_time: 5
stop_loss: 0.2
take_profit: 0.06
time_limit: 43200
trailing_stop_activation_price_delta: 0.0045
trailing_stop_trailing_delta: 0.003
natr_length: 100
