script_file_name: v2_dman_v1_config.py
exchange: binance_perpetual
trading_pairs: DOGE-USDT
leverage: 20
candles_exchange: binance_perpetual
candles_interval: 3m
order_amount: 25.0
n_levels: 5
start_spread: 1.0
step_between_orders: 0.8
order_refresh_time: 2700
cooldown_time: 5
stop_loss: 0.2
take_profit: 0.06
time_limit: 43200
trailing_stop_activation_price_delta: 0.0045
trailing_stop_trailing_delta: 0.003
natr_length: 100
