version: "3.9"
services:
  hummingbot-1:
    container_name: hummingbot-1
#    image: hummingbot/hummingbot:latest
    image: hummingbot/hummingbot:version-1.25.0
#    build:
#    context: ..
#      dockerfile: .ops/Dockerfile
    volumes:
      - "../conf/certs:/home/hummingbot/certs"
      - "../plugin/strategy/xemm:/home/hummingbot/hummingbot/strategy/xemm"
# Custom connectors
      - "../plugin/connector/exchange/whitebit:/home/hummingbot/hummingbot/connector/exchange/whitebit"
# Custom plugin
      - "../plugin/smart_components/controllers/dman.py:/home/hummingbot/hummingbot/smart_components/controllers/dman.py"
      - "../plugin/smart_components/strategy_frameworks/advanced:/home/hummingbot/hummingbot/smart_components/strategy_frameworks/advanced"
# Replace files
      - "../plugin/smart_components/models/executors.py:/home/hummingbot/hummingbot/smart_components/models/executors.py"
      - "../plugin/smart_components/executors/position_executor/position_executor.py:/home/hummingbot/hummingbot/smart_components/executors/position_executor/position_executor.py"
      - "../plugin/smart_components/executors/position_executor/data_types.py:/home/hummingbot/hummingbot/smart_components/executors/position_executor/data_types.py"
# Original files
      - "../submodule/hummingbot.git/hummingbot/smart_components/models/executors.py:/home/hummingbot/hummingbot/smart_components/models/executors_base.py"
      - "../submodule/hummingbot.git/hummingbot/smart_components/executors/position_executor/position_executor.py:/home/hummingbot/hummingbot/smart_components/executors/position_executor/position_executor_base.py"
      - "../submodule/hummingbot.git/hummingbot/smart_components/executors/position_executor/data_types.py:/home/hummingbot/hummingbot/smart_components/executors/position_executor/data_types_base.py"
# Bug bix:
      - "../plugin/core/web_assistant/rest_assistant.py:/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py"
# Bot instances
      - "../hummingbot-1_files/conf:/home/hummingbot/conf"
      - "../hummingbot-1_files/conf/connectors:/home/hummingbot/conf/connectors"
      - "../hummingbot-1_files/conf/scripts:/home/hummingbot/conf/scripts"
      - "../hummingbot-1_files/logs:/home/hummingbot/logs"
      - "../hummingbot-1_files/data:/home/hummingbot/data"
      - "../hummingbot-1_files/scripts:/home/hummingbot/scripts"
#      - "../plugin/templates/conf_xemm_strategy_TEMPLATE.yml:/home/hummingbot/hummingbot/templates/conf_xemm_strategy_TEMPLATE.yml"

#      - "../conf/strategies:/home/hummingbot/conf/strategies"
#      - "../plugin/strategy/get_order_book:/home/hummingbot/hummingbot/strategy/get_order_book"
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host

  gateway:
    container_name: gateway
#    image: hummingbot/gateway:latest
    image: hummingbot/gateway:version-1.25.0
    env_file:
      - .env
    ports:
      - "15888:15888"
      - "8080:8080"
    volumes:
      - "../gateway_files/conf:/home/gateway/conf"
      - "../gateway_files/logs:/home/gateway/logs"
      - "../gateway_files/db:/home/gateway/db"
#      - "../hummingbot_files/certs:/home/gateway/certs"
      - "../hummingbot/certs:/home/gateway/certs"
